micronaut:
  application:
    name: keyManagerGrpc
datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:`postgres`}
    password: ${DB_PASSWORD:`password`}
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show-sql: true
        format_sql: true

itau:
  url: ${ITAU_URL:`http://localhost:9091`}

bcb:
  url: ${BCB_URL:`http://localhost:8082`}